webtalk_init -webtalk_dir G:/My Drive/Work Space/Academics/CoE 113/Machine Problem 1/machine_problem/machine_problem.sim/sim_1/behav/xsim/xsim.dir/tb_controller_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Jul 16 10:24:26 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "f32a917d-8ae4-4a86-86ca-2128f4bf5e00" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "358293c6c07c4586bc1f5eec214713d1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "34" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Celeron(R) CPU N3450 @ 1.10GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1094 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "300 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.16_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6428_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2992379750 -regid "" -xml G:/My Drive/Work Space/Academics/CoE 113/Machine Problem 1/machine_problem/machine_problem.sim/sim_1/behav/xsim/xsim.dir/tb_controller_behav/webtalk/usage_statistics_ext_xsim.xml -html G:/My Drive/Work Space/Academics/CoE 113/Machine Problem 1/machine_problem/machine_problem.sim/sim_1/behav/xsim/xsim.dir/tb_controller_behav/webtalk/usage_statistics_ext_xsim.html -wdm G:/My Drive/Work Space/Academics/CoE 113/Machine Problem 1/machine_problem/machine_problem.sim/sim_1/behav/xsim/xsim.dir/tb_controller_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
