@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Mon Jun 19 20:13:03 +0800 2023
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim tb_processor_behav -key {Behavioral:sim_1:Functional:tb_processor} -tclbatch tb_processor.tcl -view C:/Users/CJ/Desktop/advanced-computer-organization/MP 1/tb_controller_behav.wcfg -view C:/Users/CJ/Desktop/advanced-computer-organization/MP 1/tb_alu_behav.wcfg -view C:/Users/CJ/Desktop/advanced-computer-organization/MP 1/tb_register_file_behav.wcfg -view C:/Users/CJ/Desktop/advanced-computer-organization/MP 1/tb_sign_extend_behav.wcfg -view C:/Users/CJ/Desktop/advanced-computer-organization/MP 1/tb_pc_behav.wcfg -view C:/Users/CJ/Desktop/advanced-computer-organization/MP 1/tb_mem_prog_behav.wcfg -view C:/Users/CJ/Desktop/advanced-computer-organization/MP 1/tb_processor_behav.wcfg -view C:/Users/CJ/Desktop/project_1/tb_top_module_behav.wcfg -view C:/Users/CJ/Desktop/project_1/tb_processor_func_synth.wcfg -log simulate.log"
call xsim  tb_processor_behav -key {Behavioral:sim_1:Functional:tb_processor} -tclbatch tb_processor.tcl -view C:/Users/CJ/Desktop/advanced-computer-organization/MP 1/tb_controller_behav.wcfg -view C:/Users/CJ/Desktop/advanced-computer-organization/MP 1/tb_alu_behav.wcfg -view C:/Users/CJ/Desktop/advanced-computer-organization/MP 1/tb_register_file_behav.wcfg -view C:/Users/CJ/Desktop/advanced-computer-organization/MP 1/tb_sign_extend_behav.wcfg -view C:/Users/CJ/Desktop/advanced-computer-organization/MP 1/tb_pc_behav.wcfg -view C:/Users/CJ/Desktop/advanced-computer-organization/MP 1/tb_mem_prog_behav.wcfg -view C:/Users/CJ/Desktop/advanced-computer-organization/MP 1/tb_processor_behav.wcfg -view C:/Users/CJ/Desktop/project_1/tb_top_module_behav.wcfg -view C:/Users/CJ/Desktop/project_1/tb_processor_func_synth.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
