@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Aug 09 23:41:29 +0800 2022
REM SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim tb_processor_behav -key {Behavioral:sim_1:Functional:tb_processor} -tclbatch tb_processor.tcl -view G:/My Drive/Work Space/Academics/CoE 113/Machine Problem 1/machine_problem/tb_controller_behav.wcfg -view G:/My Drive/Work Space/Academics/CoE 113/Machine Problem 1/machine_problem/tb_alu_behav.wcfg -view G:/My Drive/Work Space/Academics/CoE 113/Machine Problem 1/machine_problem/tb_register_file_behav.wcfg -view G:/My Drive/Work Space/Academics/CoE 113/Machine Problem 1/machine_problem/tb_sign_extend_behav.wcfg -view G:/My Drive/Work Space/Academics/CoE 113/Machine Problem 1/machine_problem/tb_pc_behav.wcfg -view G:/My Drive/Work Space/Academics/CoE 113/Machine Problem 1/machine_problem/tb_mem_prog_behav.wcfg -view G:/My Drive/Work Space/Academics/CoE 113/Machine Problem 1/machine_problem/tb_processor_behav.wcfg -log simulate.log"
call xsim  tb_processor_behav -key {Behavioral:sim_1:Functional:tb_processor} -tclbatch tb_processor.tcl -view G:/My Drive/Work Space/Academics/CoE 113/Machine Problem 1/machine_problem/tb_controller_behav.wcfg -view G:/My Drive/Work Space/Academics/CoE 113/Machine Problem 1/machine_problem/tb_alu_behav.wcfg -view G:/My Drive/Work Space/Academics/CoE 113/Machine Problem 1/machine_problem/tb_register_file_behav.wcfg -view G:/My Drive/Work Space/Academics/CoE 113/Machine Problem 1/machine_problem/tb_sign_extend_behav.wcfg -view G:/My Drive/Work Space/Academics/CoE 113/Machine Problem 1/machine_problem/tb_pc_behav.wcfg -view G:/My Drive/Work Space/Academics/CoE 113/Machine Problem 1/machine_problem/tb_mem_prog_behav.wcfg -view G:/My Drive/Work Space/Academics/CoE 113/Machine Problem 1/machine_problem/tb_processor_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
